## Overview
Our work focuses on the two-Higgs-doublet model with a softly broken $Z_2$ symmetry in the **Normal Scenario**,
where the observed 125 GeV Higgs boson is identified as the lighter CP-even neutral state ($h$).
We perform a comprehensive analysis across all four Yukawa types: **Type-I**, **Type-II**, **Type-X (Lepton-specific)**, and **Type-Y (Flipped)**.

- [arXiv:2607.09864 [hep-ph]](https://arxiv.org/abs/2607.09864) **Strong First-Order Electroweak Phase Transitions and Gravitational Waves in the Normal Two-Higgs-Doublet Model: A Comparative Study of the Four Yukawa Types and Thermal Resummation Schemes** by Jin-Hwan Cho, Dongjoo Kim, Jinheung Kim, Soojin Lee, and Jeonghyeon Song

## Gravitational Wave (GW) Parameter Points
We highlight parameter points that yield a potentially observable stochastic gravitational wave background (SGWB).
These points satisfy the detection threshold defined by a 4-year LISA signal-to-noise ratio:
$$
\text{SNR} > 10.
$$

In [1]:
import polars as pl
pl.Config.set_tbl_rows(10)

all_df = pl.read_parquet("GW_parameters.parquet")

def show_parameters(scheme):
    assert scheme in ["Parwani", "AE"]
    for yuktype in ["Type-I", "Type-II", "Type-X", "Type-Y"]:
        df = all_df.filter(
            pl.col("resummation scheme") == scheme,
            pl.col("Yukawa type") == yuktype,
        ).sort(
            by="SNR", descending=True
        )
        if len(df) > 0:
            display(df)

### Parwani resummation scheme

In [2]:
show_parameters("Parwani")

shape: (1_789, 11)
┌────────┬──────────────┬──────────┬──────────┬───┬─────────────┬───────────┬──────────┬───────────┐
│ Yukawa ┆ resummation  ┆ L1       ┆ L2       ┆ … ┆ m12sq       ┆ tbeta     ┆ xi_p     ┆ SNR       │
│ type   ┆ scheme       ┆ ---      ┆ ---      ┆   ┆ ---         ┆ ---       ┆ ---      ┆ ---       │
│ ---    ┆ ---          ┆ f64      ┆ f64      ┆   ┆ f64         ┆ f64       ┆ f64      ┆ f64       │
│ str    ┆ str          ┆          ┆          ┆   ┆             ┆           ┆          ┆           │
╞════════╪══════════════╪══════════╪══════════╪═══╪═════════════╪═══════════╪══════════╪═══════════╡
│ Type-I ┆ Parwani      ┆ 3.660331 ┆ 0.260819 ┆ … ┆ 2134.417464 ┆ 20.837126 ┆ 3.432518 ┆ 95.140179 │
│ Type-I ┆ Parwani      ┆ 2.740518 ┆ 0.262807 ┆ … ┆ 2247.197086 ┆ 20.228812 ┆ 3.265843 ┆ 82.046294 │
│ Type-I ┆ Parwani      ┆ 3.505747 ┆ 0.263265 ┆ … ┆ 3176.369956 ┆ 16.482401 ┆ 3.311331 ┆ 73.008549 │
│ Type-I ┆ Parwani      ┆ 2.803444 ┆ 0.262564 ┆ … ┆ 2133.432157 ┆ 21.104659 ┆ 3.207972 ┆ 72.020103 │
│ Type-I ┆ Parwani      ┆ 4.101739 ┆ 0.259391 ┆ … ┆ 3717.525399 ┆ 4.322233  ┆ 3.43229  ┆ 67.195421 │
│ …      ┆ …            ┆ …        ┆ …        ┆ … ┆ …           ┆ …         ┆ …        ┆ …         │
│ Type-I ┆ Parwani      ┆ 8.067333 ┆ 1.148175 ┆ … ┆ 31587.87649 ┆ 1.607754  ┆ 2.852313 ┆ 10.017942 │
│        ┆              ┆          ┆          ┆   ┆ 7           ┆           ┆          ┆           │
│ Type-I ┆ Parwani      ┆ 4.127789 ┆ 0.216031 ┆ … ┆ 16175.52249 ┆ 5.038047  ┆ 3.687301 ┆ 10.016137 │
│ Type-I ┆ Parwani      ┆ 2.418861 ┆ 0.281346 ┆ … ┆ 25035.75623 ┆ 4.87914   ┆ 3.157666 ┆ 10.015492 │
│        ┆              ┆          ┆          ┆   ┆ 6           ┆           ┆          ┆           │
│ Type-I ┆ Parwani      ┆ 5.036724 ┆ 0.538235 ┆ … ┆ 43759.89515 ┆ 1.734842  ┆ 2.900736 ┆ 10.014728 │
│        ┆              ┆          ┆          ┆   ┆ 5           ┆           ┆          ┆           │
│ Type-I ┆ Parwani      ┆ 5.528541 ┆ 0.940881 ┆ … ┆ 29680.17693 ┆ 1.762934  ┆ 3.121134 ┆ 10.01018  │
│        ┆              ┆          ┆          ┆   ┆ 4           ┆           ┆          ┆           │
└────────┴──────────────┴──────────┴──────────┴───┴─────────────┴───────────┴──────────┴───────────┘

shape: (63, 11)
┌─────────┬──────────────┬──────────┬──────────┬───┬─────────────┬──────────┬──────────┬───────────┐
│ Yukawa  ┆ resummation  ┆ L1       ┆ L2       ┆ … ┆ m12sq       ┆ tbeta    ┆ xi_p     ┆ SNR       │
│ type    ┆ scheme       ┆ ---      ┆ ---      ┆   ┆ ---         ┆ ---      ┆ ---      ┆ ---       │
│ ---     ┆ ---          ┆ f64      ┆ f64      ┆   ┆ f64         ┆ f64      ┆ f64      ┆ f64       │
│ str     ┆ str          ┆          ┆          ┆   ┆             ┆          ┆          ┆           │
╞═════════╪══════════════╪══════════╪══════════╪═══╪═════════════╪══════════╪══════════╪═══════════╡
│ Type-II ┆ Parwani      ┆ 0.390319 ┆ 0.216569 ┆ … ┆ 50418.05422 ┆ 2.197192 ┆ 3.345737 ┆ 19.376396 │
│         ┆              ┆          ┆          ┆   ┆ 2           ┆          ┆          ┆           │
│ Type-II ┆ Parwani      ┆ 1.165471 ┆ 0.183795 ┆ … ┆ 55769.47257 ┆ 1.860657 ┆ 3.283536 ┆ 16.222816 │
│         ┆              ┆          ┆          ┆   ┆ 2           ┆          ┆          ┆           │
│ Type-II ┆ Parwani      ┆ 0.987171 ┆ 0.26202  ┆ … ┆ 54681.50491 ┆ 2.203235 ┆ 3.423113 ┆ 14.533102 │
│         ┆              ┆          ┆          ┆   ┆ 4           ┆          ┆          ┆           │
│ Type-II ┆ Parwani      ┆ 1.682488 ┆ 0.281884 ┆ … ┆ 39520.89667 ┆ 2.945202 ┆ 3.390343 ┆ 14.217551 │
│         ┆              ┆          ┆          ┆   ┆ 2           ┆          ┆          ┆           │
│ Type-II ┆ Parwani      ┆ 1.052101 ┆ 0.228597 ┆ … ┆ 46007.55478 ┆ 2.854784 ┆ 3.433424 ┆ 14.073938 │
│         ┆              ┆          ┆          ┆   ┆ 1           ┆          ┆          ┆           │
│ …       ┆ …            ┆ …        ┆ …        ┆ … ┆ …           ┆ …        ┆ …        ┆ …         │
│ Type-II ┆ Parwani      ┆ 1.516311 ┆ 0.408414 ┆ … ┆ 81529.75524 ┆ 1.30535  ┆ 3.388951 ┆ 10.135485 │
│         ┆              ┆          ┆          ┆   ┆ 7           ┆          ┆          ┆           │
│ Type-II ┆ Parwani      ┆ 1.849744 ┆ 0.233451 ┆ … ┆ 54623.95848 ┆ 2.299603 ┆ 3.04696  ┆ 10.132012 │
│         ┆              ┆          ┆          ┆   ┆ 9           ┆          ┆          ┆           │
│ Type-II ┆ Parwani      ┆ 0.337173 ┆ 0.228203 ┆ … ┆ 71698.41543 ┆ 2.196599 ┆ 2.956472 ┆ 10.123033 │
│         ┆              ┆          ┆          ┆   ┆ 8           ┆          ┆          ┆           │
│ Type-II ┆ Parwani      ┆ 2.978612 ┆ 0.505057 ┆ … ┆ 63409.43113 ┆ 1.694018 ┆ 3.179037 ┆ 10.112259 │
│         ┆              ┆          ┆          ┆   ┆ 1           ┆          ┆          ┆           │
│ Type-II ┆ Parwani      ┆ 2.047495 ┆ 0.678795 ┆ … ┆ 63861.84107 ┆ 1.576663 ┆ 3.01528  ┆ 10.033673 │
│         ┆              ┆          ┆          ┆   ┆ 8           ┆          ┆          ┆           │
└─────────┴──────────────┴──────────┴──────────┴───┴─────────────┴──────────┴──────────┴───────────┘

shape: (670, 11)
┌────────┬──────────────┬──────────┬──────────┬───┬─────────────┬───────────┬──────────┬───────────┐
│ Yukawa ┆ resummation  ┆ L1       ┆ L2       ┆ … ┆ m12sq       ┆ tbeta     ┆ xi_p     ┆ SNR       │
│ type   ┆ scheme       ┆ ---      ┆ ---      ┆   ┆ ---         ┆ ---       ┆ ---      ┆ ---       │
│ ---    ┆ ---          ┆ f64      ┆ f64      ┆   ┆ f64         ┆ f64       ┆ f64      ┆ f64       │
│ str    ┆ str          ┆          ┆          ┆   ┆             ┆           ┆          ┆           │
╞════════╪══════════════╪══════════╪══════════╪═══╪═════════════╪═══════════╪══════════╪═══════════╡
│ Type-X ┆ Parwani      ┆ 3.409497 ┆ 0.257778 ┆ … ┆ 2018.1039   ┆ 14.238976 ┆ 3.338812 ┆ 60.413307 │
│ Type-X ┆ Parwani      ┆ 1.523805 ┆ 0.257663 ┆ … ┆ 4217.293047 ┆ 8.935474  ┆ 3.550339 ┆ 52.105082 │
│ Type-X ┆ Parwani      ┆ 0.11163  ┆ 0.257456 ┆ … ┆ 3486.501625 ┆ 11.299636 ┆ 3.528823 ┆ 51.999941 │
│ Type-X ┆ Parwani      ┆ 0.227063 ┆ 0.256683 ┆ … ┆ 4865.729289 ┆ 9.159153  ┆ 3.465136 ┆ 51.93704  │
│ Type-X ┆ Parwani      ┆ 2.04366  ┆ 0.257512 ┆ … ┆ 2487.108208 ┆ 11.331618 ┆ 3.565191 ┆ 51.447072 │
│ …      ┆ …            ┆ …        ┆ …        ┆ … ┆ …           ┆ …         ┆ …        ┆ …         │
│ Type-X ┆ Parwani      ┆ 2.047495 ┆ 0.678795 ┆ … ┆ 63861.84107 ┆ 1.576663  ┆ 3.015236 ┆ 10.040926 │
│        ┆              ┆          ┆          ┆   ┆ 8           ┆           ┆          ┆           │
│ Type-X ┆ Parwani      ┆ 0.831718 ┆ 0.257508 ┆ … ┆ 7856.779098 ┆ 11.326803 ┆ 3.123152 ┆ 10.040316 │
│ Type-X ┆ Parwani      ┆ 4.526789 ┆ 1.193733 ┆ … ┆ 40131.66902 ┆ 1.562728  ┆ 3.185836 ┆ 10.024683 │
│        ┆              ┆          ┆          ┆   ┆ 8           ┆           ┆          ┆           │
│ Type-X ┆ Parwani      ┆ 8.067333 ┆ 1.148175 ┆ … ┆ 31587.87649 ┆ 1.607754  ┆ 2.852313 ┆ 10.022213 │
│        ┆              ┆          ┆          ┆   ┆ 7           ┆           ┆          ┆           │
│ Type-X ┆ Parwani      ┆ 4.826022 ┆ 0.505947 ┆ … ┆ 67718.66220 ┆ 1.668481  ┆ 3.611595 ┆ 10.001352 │
│        ┆              ┆          ┆          ┆   ┆ 4           ┆           ┆          ┆           │
└────────┴──────────────┴──────────┴──────────┴───┴─────────────┴───────────┴──────────┴───────────┘

shape: (61, 11)
┌────────┬──────────────┬──────────┬──────────┬───┬──────────────┬──────────┬──────────┬───────────┐
│ Yukawa ┆ resummation  ┆ L1       ┆ L2       ┆ … ┆ m12sq        ┆ tbeta    ┆ xi_p     ┆ SNR       │
│ type   ┆ scheme       ┆ ---      ┆ ---      ┆   ┆ ---          ┆ ---      ┆ ---      ┆ ---       │
│ ---    ┆ ---          ┆ f64      ┆ f64      ┆   ┆ f64          ┆ f64      ┆ f64      ┆ f64       │
│ str    ┆ str          ┆          ┆          ┆   ┆              ┆          ┆          ┆           │
╞════════╪══════════════╪══════════╪══════════╪═══╪══════════════╪══════════╪══════════╪═══════════╡
│ Type-Y ┆ Parwani      ┆ 0.390319 ┆ 0.216569 ┆ … ┆ 50418.054222 ┆ 2.197192 ┆ 3.345735 ┆ 19.37639  │
│ Type-Y ┆ Parwani      ┆ 0.098519 ┆ 0.186548 ┆ … ┆ 55624.288885 ┆ 2.25568  ┆ 3.319296 ┆ 17.835971 │
│ Type-Y ┆ Parwani      ┆ 0.987171 ┆ 0.26202  ┆ … ┆ 54681.504914 ┆ 2.203235 ┆ 3.423112 ┆ 14.533411 │
│ Type-Y ┆ Parwani      ┆ 1.303626 ┆ 0.493674 ┆ … ┆ 59044.769169 ┆ 1.704863 ┆ 3.345099 ┆ 14.401192 │
│ Type-Y ┆ Parwani      ┆ 1.016316 ┆ 0.286961 ┆ … ┆ 44465.144405 ┆ 2.774685 ┆ 3.118024 ┆ 13.991323 │
│ …      ┆ …            ┆ …        ┆ …        ┆ … ┆ …            ┆ …        ┆ …        ┆ …         │
│ Type-Y ┆ Parwani      ┆ 2.978612 ┆ 0.505057 ┆ … ┆ 63409.431131 ┆ 1.694018 ┆ 3.179037 ┆ 10.110672 │
│ Type-Y ┆ Parwani      ┆ 1.577091 ┆ 0.605359 ┆ … ┆ 73642.586546 ┆ 1.591103 ┆ 3.24953  ┆ 10.110475 │
│ Type-Y ┆ Parwani      ┆ 2.047495 ┆ 0.678795 ┆ … ┆ 63861.841078 ┆ 1.576663 ┆ 3.015289 ┆ 10.034288 │
│ Type-Y ┆ Parwani      ┆ 0.344771 ┆ 0.279371 ┆ … ┆ 44052.198634 ┆ 4.507597 ┆ 3.324956 ┆ 10.030765 │
│ Type-Y ┆ Parwani      ┆ 2.152765 ┆ 0.265593 ┆ … ┆ 56932.362908 ┆ 2.230166 ┆ 3.14817  ┆ 10.021154 │
└────────┴──────────────┴──────────┴──────────┴───┴──────────────┴──────────┴──────────┴───────────┘

### AE (Arnold-Espinosa) resummation scheme

In [3]:
show_parameters("AE")

shape: (110, 11)
┌────────┬─────────────┬──────────┬──────────┬───┬─────────────┬───────────┬──────────┬────────────┐
│ Yukawa ┆ resummation ┆ L1       ┆ L2       ┆ … ┆ m12sq       ┆ tbeta     ┆ xi_p     ┆ SNR        │
│ type   ┆ scheme      ┆ ---      ┆ ---      ┆   ┆ ---         ┆ ---       ┆ ---      ┆ ---        │
│ ---    ┆ ---         ┆ f64      ┆ f64      ┆   ┆ f64         ┆ f64       ┆ f64      ┆ f64        │
│ str    ┆ str         ┆          ┆          ┆   ┆             ┆           ┆          ┆            │
╞════════╪═════════════╪══════════╪══════════╪═══╪═════════════╪═══════════╪══════════╪════════════╡
│ Type-I ┆ AE          ┆ 0.380511 ┆ 0.25345  ┆ … ┆ 5068.536568 ┆ 7.622886  ┆ 5.24935  ┆ 195.109047 │
│ Type-I ┆ AE          ┆ 1.005413 ┆ 0.296279 ┆ … ┆ 5114.953127 ┆ 5.495746  ┆ 5.226148 ┆ 185.28196  │
│ Type-I ┆ AE          ┆ 0.178467 ┆ 0.263267 ┆ … ┆ 2752.136651 ┆ 15.468622 ┆ 5.165821 ┆ 183.366928 │
│ Type-I ┆ AE          ┆ 0.859106 ┆ 0.240688 ┆ … ┆ 8519.253175 ┆ 5.878623  ┆ 4.992479 ┆ 163.094197 │
│ Type-I ┆ AE          ┆ 0.2138   ┆ 0.273129 ┆ … ┆ 6901.089789 ┆ 4.421425  ┆ 5.010347 ┆ 148.292416 │
│ …      ┆ …           ┆ …        ┆ …        ┆ … ┆ …           ┆ …         ┆ …        ┆ …          │
│ Type-I ┆ AE          ┆ 0.106556 ┆ 0.263575 ┆ … ┆ 9618.425009 ┆ 3.535882  ┆ 3.905539 ┆ 10.661741  │
│ Type-I ┆ AE          ┆ 0.523794 ┆ 0.24577  ┆ … ┆ 6569.405093 ┆ 5.335515  ┆ 3.863298 ┆ 10.404665  │
│ Type-I ┆ AE          ┆ 0.96847  ┆ 0.254671 ┆ … ┆ 5845.588818 ┆ 3.98526   ┆ 3.502449 ┆ 10.176015  │
│ Type-I ┆ AE          ┆ 1.134894 ┆ 0.241042 ┆ … ┆ 8263.73563  ┆ 5.170311  ┆ 3.786276 ┆ 10.1223    │
│ Type-I ┆ AE          ┆ 2.670937 ┆ 0.24368  ┆ … ┆ 7609.56531  ┆ 3.942548  ┆ 3.653422 ┆ 10.063307  │
└────────┴─────────────┴──────────┴──────────┴───┴─────────────┴───────────┴──────────┴────────────┘

shape: (1, 11)
┌────────┬──────────────┬──────────┬──────────┬───┬──────────────┬───────────┬──────────┬──────────┐
│ Yukawa ┆ resummation  ┆ L1       ┆ L2       ┆ … ┆ m12sq        ┆ tbeta     ┆ xi_p     ┆ SNR      │
│ type   ┆ scheme       ┆ ---      ┆ ---      ┆   ┆ ---          ┆ ---       ┆ ---      ┆ ---      │
│ ---    ┆ ---          ┆ f64      ┆ f64      ┆   ┆ f64          ┆ f64       ┆ f64      ┆ f64      │
│ str    ┆ str          ┆          ┆          ┆   ┆              ┆           ┆          ┆          │
╞════════╪══════════════╪══════════╪══════════╪═══╪══════════════╪═══════════╪══════════╪══════════╡
│ Type-X ┆ AE           ┆ 0.390944 ┆ 0.257312 ┆ … ┆ 3043.602881  ┆ 14.485503 ┆ 4.131516 ┆ 54.27005 │
└────────┴──────────────┴──────────┴──────────┴───┴──────────────┴───────────┴──────────┴──────────┘